- _target_: imenhance.GlobalHistogramEqualization
  params:
    name: GlobalHistogramEqualization
- _target_: imenhance.GammaCorrection
  params:
    name: GammaCorrection
    gamma:
        range: [0.1, 3.0]
        step: 0.1
        default: 1
- _target_: imenhance.LocalHistogramEqualization
  params:
    name: CLAHE
    clip_limit:
      range: [1.0, 4.0]
      step: 0.1
      default: 1
    tile_grid_size:
      range: [3, 15]
      step: 1
      default: 5
